apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-cep
  description: API RESTful para consulta de CEP brasileiro via ViaCEP
  tags:
    - rest
    - fastapi
    - cep
    - brasil
  links:
    - url: http://localhost:8000/docs
      title: Swagger UI
      icon: docs
    - url: https://viacep.com.br
      title: ViaCEP (Serviço Base)
      icon: web
spec:
  type: openapi
  lifecycle: experimental
  owner: group:default/team-cep
  definition: |
    openapi: 3.0.0
    info:
      title: API de CEP
      version: 1.0.0
      description: Consulta CEP brasileiro
    paths:
      /cep/{cep}:
        get:
          summary: Consultar CEP
          parameters:
            - name: cep
              in: path
              required: true
              schema:
                type: string
          responses:
            '200':
              description: CEP encontrado
            '404':
              description: CEP não encontrado
